# Travis CI pipeline demo : integration with the MOABI REST API
language: c
jobs:
  include:
    - stage: build
      script: make
    - stage: test
      script:
      - make
      - ls
      - curl -X "POST" "https://${moabi_host}/api/uploads" -H "accept:application/ld+json" -H "apikey:${moabi_api_key}" -H "Content-Type:multipart/form-data" -F "software=@./hello" -o moabi.id.json
      - BINARYID=`grep "[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*" -o moabi.id.json`
      - echo "UUID ${BINARYID}"
      - echo "Waiting on ${BINARYID}"
      - MOABISTATUS="INITIAL"
      - while [ "$MOABISTATUS" != "SCANNED" ] ; do
      - sleep 60
      - curl -X "GET" "https://${moabi_host}/api/uploads/${BINARYID}" -H "accept:application/ld+json" -H "apikey:${moabi_api_key}" -o moabi.status.json
      - MOABISTATUS="$(cat moabi.status.json| tr ',' "\n" | grep status |awk -F "\:" '{print $2}'|tr -d '"')"
      - echo "CURRENT STATUS '${MOABISTATUS}'"
      - done
      - echo "analysis performed"
      - MOABIRESULTS=`cat moabi.status.json| tr ',' "\n" | grep KPIsStatus |awk -F "\:" '{print $2}'|tr -d '"'`
      - echo "RESULTS ${MOABIRESULTS}"
      - if [ $MOABIRESULTS == "PASS" ] ; then
      - echo "Build successful"
      - else
      - echo "Build failed"
      - exit -1
      - fi
      - echo "Tests complete."
