# Travis CI pipeline demo : integration with the MOABI REST API
language: c
jobs:
  include:
    - stage: build
      script: make
    - stage: test
      script:
      - make
      - ls
      - curl -X "POST" "https://${moabi_host}/api/uploads" -H "accept:application/ld+json" -H "apikey:${moabi_api_key}" -H "Content-Type:multipart/form-data" -F "software=@./hello" -o moabi.id.json
      - BINARYID=`grep "[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*" -o moabi.id.json`
      - echo "UUID ${BINARYID}"
      - echo "Waiting on ${BINARYID}"
      - MOABISTATUS="INITIAL"

